# Generated by Django 3.1.5 on 2021-04-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0004_auto_20210427_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractDataFromAPIModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255)),
                ('dress_type', models.CharField(max_length=100)),
                ('schema_format', models.JSONField()),
            ],
        ),
    ]
