# Generated by Django 3.1.5 on 2021-04-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0005_extractdatafromapimodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtractDataFromAPIModel',
        ),
    ]
